CC=g++
obj= copy_constructor_1 \
	 copy_constructor_2 \
	 copy_constructor_3 \
	 copy_constructor_4 \
	 copy_constructor_5 \
	 copy_constructor_6 \

#example:\
	#copy_constructor_1\
	#copy_constructor_2


all:$(obj)
	@echo "compile all"

clean:
	rm -rf $(obj)
